/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'orderCount' : bigint,
  'topProducts' : Array<ProductSales>,
  'totalRevenue' : bigint,
}
export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Customer {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'addresses' : Array<ShippingAddress>,
}
export type Error = { 'InvalidInput' : string } |
  { 'OutOfStock' : string } |
  { 'NotFound' : string } |
  { 'Unauthorized' : string } |
  { 'AlreadyExists' : string };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'customerId' : UserId,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'rating' : number,
  'price' : bigint,
}
export type ProductCategory = { 'Food' : null } |
  { 'Books' : null } |
  { 'Other' : null } |
  { 'Beauty' : null } |
  { 'Electronics' : null } |
  { 'HomeGarden' : null } |
  { 'Clothing' : null } |
  { 'Sports' : null };
export type ProductId = bigint;
export interface ProductSales {
  'revenue' : bigint,
  'name' : string,
  'productId' : ProductId,
  'totalSold' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Result_1 = { 'ok' : Customer } |
  { 'err' : Error };
export type Result_2 = { 'ok' : Product } |
  { 'err' : Error };
export type Result_3 = { 'ok' : Order } |
  { 'err' : Error };
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'state' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'Customer' : null } |
  { 'Admin' : null };
export interface _SERVICE {
  'addAddress' : ActorMethod<[ShippingAddress], Result_1>,
  'addToCart' : ActorMethod<[ProductId, bigint], Result>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, ProductCategory, bigint],
    Result_2
  >,
  'deleteProduct' : ActorMethod<[ProductId], Result>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getMyProfile' : ActorMethod<[], [] | [Customer]>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[[] | [ProductCategory]], Array<Product>>,
  'placeOrder' : ActorMethod<[ShippingAddress], Result_3>,
  'registerCustomer' : ActorMethod<[string, string], Result_1>,
  'removeFromCart' : ActorMethod<[ProductId], Result>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setCustomerRole' : ActorMethod<[UserId, UserRole], Result_1>,
  'updateCartItem' : ActorMethod<[ProductId, bigint], Result>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], Result_3>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [ProductCategory],
      [] | [bigint],
      [] | [boolean],
    ],
    Result_2
  >,
  'updateProfile' : ActorMethod<[[] | [string], [] | [string]], Result_1>,
  'uploadProductImage' : ActorMethod<[ProductId, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];