/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserRole = IDL.Variant({
  'Customer' : IDL.Null,
  'Admin' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(ShippingAddress),
});
export const Error = IDL.Variant({
  'InvalidInput' : IDL.Text,
  'OutOfStock' : IDL.Text,
  'NotFound' : IDL.Text,
  'Unauthorized' : IDL.Text,
  'AlreadyExists' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : Customer, 'err' : Error });
export const ProductId = IDL.Nat;
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ProductCategory = IDL.Variant({
  'Food' : IDL.Null,
  'Books' : IDL.Null,
  'Other' : IDL.Null,
  'Beauty' : IDL.Null,
  'Electronics' : IDL.Null,
  'HomeGarden' : IDL.Null,
  'Clothing' : IDL.Null,
  'Sports' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : Product, 'err' : Error });
export const ProductSales = IDL.Record({
  'revenue' : IDL.Nat,
  'name' : IDL.Text,
  'productId' : ProductId,
  'totalSold' : IDL.Nat,
});
export const Analytics = IDL.Record({
  'orderCount' : IDL.Nat,
  'topProducts' : IDL.Vec(ProductSales),
  'totalRevenue' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'customerId' : UserId,
  'items' : IDL.Vec(OrderItem),
});
export const Result_3 = IDL.Variant({ 'ok' : Order, 'err' : Error });

export const idlService = IDL.Service({
  'addAddress' : IDL.Func([ShippingAddress], [Result_1], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [Result], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ProductCategory, IDL.Nat],
      [Result_2],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [Result], []),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Customer)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(ProductCategory)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([ShippingAddress], [Result_3], []),
  'registerCustomer' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'removeFromCart' : IDL.Func([ProductId], [Result], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setCustomerRole' : IDL.Func([UserId, UserRole], [Result_1], []),
  'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [Result], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Result_3], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(ProductCategory),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
      ],
      [Result_2],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'uploadProductImage' : IDL.Func([ProductId, IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserRole = IDL.Variant({ 'Customer' : IDL.Null, 'Admin' : IDL.Null });
  const Customer = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(ShippingAddress),
  });
  const Error = IDL.Variant({
    'InvalidInput' : IDL.Text,
    'OutOfStock' : IDL.Text,
    'NotFound' : IDL.Text,
    'Unauthorized' : IDL.Text,
    'AlreadyExists' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : Customer, 'err' : Error });
  const ProductId = IDL.Nat;
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ProductCategory = IDL.Variant({
    'Food' : IDL.Null,
    'Books' : IDL.Null,
    'Other' : IDL.Null,
    'Beauty' : IDL.Null,
    'Electronics' : IDL.Null,
    'HomeGarden' : IDL.Null,
    'Clothing' : IDL.Null,
    'Sports' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : Product, 'err' : Error });
  const ProductSales = IDL.Record({
    'revenue' : IDL.Nat,
    'name' : IDL.Text,
    'productId' : ProductId,
    'totalSold' : IDL.Nat,
  });
  const Analytics = IDL.Record({
    'orderCount' : IDL.Nat,
    'topProducts' : IDL.Vec(ProductSales),
    'totalRevenue' : IDL.Nat,
  });
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'customerId' : UserId,
    'items' : IDL.Vec(OrderItem),
  });
  const Result_3 = IDL.Variant({ 'ok' : Order, 'err' : Error });
  
  return IDL.Service({
    'addAddress' : IDL.Func([ShippingAddress], [Result_1], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [Result], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ProductCategory, IDL.Nat],
        [Result_2],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [Result], []),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Customer)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(ProductCategory)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([ShippingAddress], [Result_3], []),
    'registerCustomer' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'removeFromCart' : IDL.Func([ProductId], [Result], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setCustomerRole' : IDL.Func([UserId, UserRole], [Result_1], []),
    'updateCartItem' : IDL.Func([ProductId, IDL.Nat], [Result], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Result_3], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(ProductCategory),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
        ],
        [Result_2],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'uploadProductImage' : IDL.Func([ProductId, IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };